# Generated by Django 5.0.3 on 2024-08-01 14:29

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Category = apps.get_model('store','Category')
    Product = apps.get_model('store', 'Product')
    Size = apps.get_model('store','Size')
    SizeConvention = apps.get_model('store','SizeConvention')
    Inventory = apps.get_model('store', 'Inventory')

    # Creating sizes
    JeansSizes = SizeConvention.objects.create(name='Jeans Sizes')
    ClothingSizes = SizeConvention.objects.create(name='Clothing Sizes')
    Size.objects.create(name='S', convention=ClothingSizes)
    Size.objects.create(name='M', convention=ClothingSizes)
    Size.objects.create(name='L', convention=ClothingSizes)
    Size.objects.create(name='XL', convention=ClothingSizes)
    for i in range(32,47,2):
        Size.objects.create(name=str(i), convention=JeansSizes)

    # Creating Categories and products
    Jackets = Category.objects.create(name='Jackets', slug='jackets')
    Jeans = Category.objects.create(name='Jeans', slug='jeans')
    Knit = Category.objects.create(name='Knit', slug='knit')
    Shirts = Category.objects.create(name='Shirts', slug='Shirts')
    Shorts = Category.objects.create(name='Shorts', slug='Shorts')
    SweatshirtsAndHoodies = Category.objects.create(name='Sweatshirts & Hoodies', slug='sweatshirts-and-hoodies')
    Swimwear = Category.objects.create(name='Swimwear', slug='swimwear')
    Trousers = Category.objects.create(name='Trousers', slug='trousers')
    Tshirts = Category.objects.create(name='T-Shirts', slug='t-shirts')
    Underwear = Category.objects.create(name='Underwear', slug='underwear')
    
    Product.objects.create(name='T-Shirt Book Print',
                           description='T-Shirt Book Print',
                           category=Tshirts,
                           slug='tshirt-bookshelf-print',
                           price=12.99,
                           image='t-shirt-design-2336850_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Red Bomber Jacket',
                           description='Red Bomber Jacket with modern print',
                           category=Jackets,
                           slug='red-bomber-jacket',
                           price=59.99,
                           image='man-8493244_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Neon Green Hoodie',
                           description='Neon Green Hoodie with zip and pockets',
                           category=SweatshirtsAndHoodies,
                           slug='neon-green-hoodie',
                           price=49.99,
                           image='man-1283576_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Jean Jacket With Gray Sleeves',
                           description='Jeans Jacket With Gray Sleeves',
                           category=Jackets,
                           slug='jeans-jackets-gray-sleeves',
                           price=29.99,
                           image='people-6889599_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Ripped Gray Jeans Jackets',
                           description='Ripped Gray Jeans Jackets',
                           category=Jackets,
                           slug='ripped-jacket',
                           price=39.99,
                           image='man-7506912_1280_f1bgfHM.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Relaxed Gray Jeans',
                           description='Relaxed Grey Jeans With Pockets',
                           category=Jeans,
                           slug='relaxed-gray-jean',
                           price=39.99,
                           image='lonely-814631_1280.jpg',
                           size_convention=JeansSizes)
    Product.objects.create(name='Ripped Skinny Jean',
                           description='Ripped Skinny Jeans with modern prints',
                           category=Jeans,
                           slug='ripped-skinny-jeans',
                           price=49.99,
                           image='bag-1850053_1280.jpg',
                           size_convention=JeansSizes)
    Product.objects.create(name='Classic Biker Leather Jacket',
                           description='Classic  Biker Leather Jacket | Made Of Faux-Leather',
                           category=Jackets,
                           slug='biker-jacket',
                           price=69.99,
                           image='ai-generated-8740190_1280.png',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Tank Top Emo Print',
                           description='Tank Top with Emo Print | Made Of Cottont',
                           category=Tshirts,
                           slug='tank-top-emo',
                           price=9.99,
                           image='dido-stargaze-6516906_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Worker Jacket',
                           description='Worker Jackets with Pockets and STWD logo',
                           category=Jackets,
                           slug='worker-jacket',
                           price=39.99,
                           image='man-6629597_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Colorful Exotic Shirt',
                           description='Colorful Exotic Shirt For Summer | Exotic Print | Made Of Cotton',
                           category=Shirts,
                           slug='exotic-shirt',
                           price=29.99,
                           image='man-6845278_1280.jpg',
                           size_convention=ClothingSizes)
    Product.objects.create(name='Ripped Baggy Jeans',
                           description='Ripped Baggy Jeans | Pale Blue | Made Of Cotton',
                           category=Jeans,
                           slug='ripped-baggy-jeans',
                           price=39.99,
                           image='jeans-499387_1280.jpg',
                           size_convention=JeansSizes)
    Product.objects.create(name='Armani Faux-Leather Jacket',
                           description='Oversize Armani Faux-Leather Jackets with pockets and zips.',
                           category=Jackets,
                           slug='aramani-jacket',
                           price=89.99,
                           image='jacket-1866572_1280.jpg',
                           size_convention=ClothingSizes)
    
    # Creating Inventory
    created_products = Product.objects.all()
    for product in created_products:
        sizes = Size.objects.filter(convention=product.size_convention)
        for size in sizes:
            Inventory.objects.create(product=product, size=size)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
