# Generated by Django 5.0.6 on 2024-06-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeConvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='size_convention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizeconvention'),
        ),
        migrations.AddField(
            model_name='size',
            name='convention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizeconvention'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('name', 'convention')},
        ),
    ]
