# Generated by Django 5.0.6 on 2024-06-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sizeconvention_alter_size_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sizeconvention'),
        ),
        migrations.AlterField(
            model_name='size',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sizeconvention'),
        ),
    ]
